name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fwilhe2/laughing-bassoon@main
      id: app
    - name: run
      run: |
        ${{ steps.app.outputs.exe }}
